data:
  num_classes: 1
  ignore_label: 255
  training_size: 3712

train:
  seed: 15
  deterministic: False

dataset:
  name: kitti
  root: gdrive/MyDrive/KITTI
  data_path: /data_object_velodyne/training/velodyne
  crm_path: /center_response_map_2D/training/crm
  num_points: 40000
  voxel_size: 0.05

num_epochs: 15
batch_size: 4
workers_per_gpu: 2
save_dir: gdrive/MyDrive/spvnas/checkpoints
save_dir_2: gdrive/MyDrive/spvnas/runs
out_save_dir: gdrive/MyDrive/KITTI/outputs

model:
  name: spvcnn

criterion:
  name: mse

optimizer:
  name: adam
  lr: 2.4e-1
  weight_decay: 1.0e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: cosine_warmup
