data:
  input_channels: 5
  num_classes: 1
  ignore_label: 255
  training_size: 3712

train:
  seed: 15
  deterministic: False

dataset:
  name: kitti
  root: /data
  data_path: dataset/kitti/object/training/velodyne
  crm_path: Ezgi/center_response_map_r2_gs
  labels_path: dataset/kitti/object/training/label_2
  calibs_path: dataset/kitti/object/training/calib
  planes_path: Ezgi/plane_models
  num_points: 20000
  voxel_size: 0.05
  quantization_size: 3
  radius: 2

num_epochs: 5
prm:
  win_size: 5
  peak_threshold: 0.8
  iou_threshold: 0.3

batch_size: 8
batch_norm: true
workers_per_gpu: 2
best_model: /data/Ezgi/best_model
checkpoints: /data/Ezgi/checkpoints
tfevent: /data/Ezgi/runs
tfeventname: /dummy

outputs_: /data/Ezgi/CenterPoint/data/kitti_prm/training/prm
outputs: /data/Ezgi/dummy
model:
  name: spvnas_cnn
  no_bn: false

criterion:
  name: mse

optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0.0
  momentum: 0.9
  nesterov: true

scheduler:
  name: cosine_warmup
