data:
  num_classes: 1
  ignore_label: 255
  training_size: 100

train:
  seed: 15
  deterministic: False

dataset:
  name: kitti
  root: gdrive/MyDrive/KITTI
  data_path: /data_object_velodyne/training/velodyne
  crm_path: /center_response_maps
  num_points: 20000
  voxel_size: 0.05
  quantization_size: 3
  
num_epochs: 1
batch_size: 4
no_bn: false
workers_per_gpu: 2
best_model: gdrive/MyDrive/spvnas/best_model
checkpoints: gdrive/MyDrive/spvnas/checkpoints
outputs: gdrive/MyDrive/KITTI/outputs_w_prm_2

model:
  name: spvnas

criterion:
  name: mse

optimizer:
  name: adam
  lr: 1.0e-1
  weight_decay: 1.0e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: cosine_warmup
