data:
  input_channels: 4
  num_classes: 1
  ignore_label: 255
  training_size: 3712

train:
  seed: 15
  deterministic: False

dataset:
  name: kitti
  root: /data
  data_path: dataset/kitti/object/training/velodyne_gs
  crm_path: Ezgi/center_response_map_r2_gs
  labels_path: dataset/kitti/object/training/label_2
  calibs_path: dataset/kitti/object/training/calib
  planes_path: Ezgi/planes
  num_points: 20000
  voxel_size: 0.05
  quantization_size: 3
  
num_epochs: 20
prm:
  win_size: 5
  peak_threshold: 0.15

batch_size: 8
batch_norm: true
workers_per_gpu: 2
best_model: /data/Ezgi/best_model
checkpoints: /data/Ezgi/checkpoints
tfevent: /data/Ezgi/runs
tfeventname: /lr0,1-bs8-r2-train-gs-shrinkage

outputs: /data/Ezgi/r2

model:
  name: spvnas
  no_bn: false

criterion:
  name: shrinkage

optimizer:
  name: adam
  lr: 1.0e-1
  weight_decay: 1.0e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: cosine_warmup
