data:
  num_classes: 1
  ignore_label: 255
  training_size: 3712

train:
  seed: 15
  deterministic: False

dataset:
  name: kitti
  root: /data
  data_path: dataset/kitti/object/training/velodyne
  crm_path: Ezgi/center_response_maps_r2
  num_points: 50000
  voxel_size: 0.05
  quantization_size: 3
  
num_epochs: 100
batch_size: 2
no_bn: false
workers_per_gpu: 2
best_model: Ezgi/best_model
checkpoints: Ezgi/checkpoints
outputs: Ezgi/outputs

model:
  name: spvnas

criterion:
  name: mse

optimizer:
  name: adam
  lr: 1.0e-1
  weight_decay: 1.0e-4
  momentum: 0.9
  nesterov: true

scheduler:
  name: cosine_warmup
